### PR TITLE
Setup chatbot

### LINKED ISSUE #3: Say Hi!
As a first step I want to be able to talk to the bot, saying "Hi" or "Hello" and get a reply back. Saying one of those two words should restart the conversasion.

This task involves creating the first core of the bot and setting it up on a server. The bot should have all the keys and permissions to chat with the selected app (Facebook or Slack)

### PR DESCRIPTION
**Pull request by EderikAlexander**
Hi @bensventures,

We coded the first setup of the bot. We started a new rails project with the devise template. Maybe a litte bit to much but i can not harm and we know how to work with it. The keys and tokens are now based on our test account until you got your facebook working again. Please check this code, and let me know if everything is ok. I can merge it then after it.   

closes #3

### CODE REVIEW

**Comment by bensventures** [comment]
Are those `.cache` supposed to be in the repo? This sounds like we need to update the `.gitignore` to exclude those. And the `.log` files too.

**Comment by EderikAlexander** [comment]
@bensventures what will happen if we just delete the temp folder with the .cache in it?

**Comment by EderikAlexander** [comment]
Hi @bensventures, 

Is this what you mean? Can you merge?

**Comment by bensventures** [comment]
Yes but you still need to remove the previously committed files from git. Right now they still show in the diff when I want to merge and they should not be there.

**Comment by EderikAlexander** [comment]
Oke, i will take them away.

**Comment by bensventures** [comment]
Just realised you also committed a .yml with the config keys. This should also be out of the commit and in the ignore. You should never, ever, commit you keys, everyone can see them here 😄

**Comment by bensventures** [comment]
@EderikAlexander How are you getting on with this? It would be nice to be able to merge so the team can carry on working on the rest

**Comment by EderikAlexander** [comment]
@bensventures everything should be fixed now in the branche. Can we merge?

**Comment by bensventures** [comment]
I still see all the `.cache` files in the diff as well as the `.log` and the `.yml`. Can you remove them from the repo? If I merge right now, all if those files will be merged as well which would be wrong.

Have a look at the `files changed` tab to see what I mean: https://github.com/Daysk/daysk-bot/pull/7/files

Some pointers, specifically the second answer:
https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-git-repo

**Comment by EderikAlexander** [comment]
Ah sorry you are right. I only deleted it on the branche not the master.

**Comment by bensventures** [comment]
Mm actually I was wrong, didn't realise those files were `removed` in the diff. No need to delete from master, merging should take care of that

**Comment by EderikAlexander** [comment]
Ok i did try to remove on the master the temp file but if you merge now everything will be fine. Will you merge?

**Comment by bensventures** [comment]
Done!

Great work :)

**Pull request merged**
